import React from 'react'
import { WhitePaper } from '../../lib/supabase'
import { Sparkles, BookOpen, Lightbulb, Brain } from 'lucide-react'

interface AIInsightsProps {
  paper: WhitePaper
}

export default function AIInsights({ paper }: AIInsightsProps) {
  const { ai_summary, ai_sections } = paper

  return (
    <div className="p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header */}
        <div className="text-center border-b border-slate-200 pb-6">
          <div className="flex items-center justify-center mb-4">
            <div className="p-3 bg-gradient-to-r from-purple-100 to-blue-100 rounded-xl">
              <Brain className="h-8 w-8 text-purple-600" />
            </div>
          </div>
          <h2 className="text-2xl font-bold text-slate-900 mb-2">AI-Powered Analysis</h2>
          <p className="text-slate-600">
            Intelligent insights and section-by-section explanations generated by Google Gemini
          </p>
        </div>

        {/* Summary Section */}
        {ai_summary && (
          <div className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-xl p-6">
            <div className="flex items-center mb-4">
              <Sparkles className="h-6 w-6 text-purple-600 mr-3" />
              <h3 className="text-xl font-semibold text-slate-900">Comprehensive Summary</h3>
            </div>
            <div className="prose prose-slate max-w-none">
              <p className="text-slate-700 leading-relaxed text-lg">
                {ai_summary}
              </p>
            </div>
          </div>
        )}

        {/* Sections Analysis */}
        {ai_sections && ai_sections.length > 0 && (
          <div className="space-y-6">
            <div className="flex items-center">
              <BookOpen className="h-6 w-6 text-blue-600 mr-3" />
              <h3 className="text-xl font-semibold text-slate-900">Section-by-Section Analysis</h3>
            </div>
            
            <div className="space-y-4">
              {ai_sections.map((section, index) => (
                <div key={index} className="bg-white border border-slate-200 rounded-lg overflow-hidden">
                  <div className="bg-slate-50 px-6 py-4 border-b border-slate-200">
                    <div className="flex items-center">
                      <div className="w-6 h-6 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-sm font-medium mr-3">
                        {index + 1}
                      </div>
                      <h4 className="text-lg font-semibold text-slate-900">
                        {section.title}
                      </h4>
                    </div>
                  </div>
                  <div className="p-6">
                    <div className="prose prose-slate max-w-none">
                      <p className="text-slate-700 leading-relaxed">
                        {section.content}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* No AI Data Fallback */}
        {(!ai_summary && (!ai_sections || ai_sections.length === 0)) && (
          <div className="text-center py-12">
            <div className="mx-auto w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
              <Lightbulb className="h-8 w-8 text-slate-400" />
            </div>
            <h3 className="text-lg font-medium text-slate-900 mb-2">AI Analysis Coming Soon</h3>
            <p className="text-slate-600">
              AI-powered insights and analysis for this paper are being processed. Please check back later.
            </p>
          </div>
        )}

        {/* AI Disclaimer */}
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
          <div className="flex items-start">
            <Lightbulb className="h-5 w-5 text-amber-600 mr-3 mt-0.5 flex-shrink-0" />
            <div>
              <h4 className="font-medium text-amber-800 mb-1">AI-Generated Content</h4>
              <p className="text-sm text-amber-700 leading-relaxed">
                These insights are generated by AI and should be used as a supplementary tool for understanding the research. 
                Always refer to the original paper for complete and authoritative information.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
